/////////////////////////////////////////////////////////////////
//															   //
// This code is generated by a tool                            //
// https://github.com/StevenThuriot/dotnet-openapi-generator   //
//															   //
/////////////////////////////////////////////////////////////////

#nullable enable

#pragma warning disable CS8618 // Non-nullable variable must contain a non-null value when exiting constructor. Consider declaring it as nullable.

namespace generate.Models;

[System.CodeDom.Compiler.GeneratedCode("dotnet-openapi-generator", "8.0.0-preview.15+2dc8cfca012adb9b7e1a243f167db99da7b5cfe4")]
[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public sealed class Whisky : __ICanIterate
{
    [System.Text.Json.Serialization.JsonConstructor] public Whisky() { }

    public Whisky(string id, string name, int age, string type, string distillery, string region)
    {
        Id = id;
        Name = name;
        Age = age;
        Type = type;
        Distillery = distillery;
        Region = region;
    }

	public string Id { get; set; }
	public string Name { get; set; }
	public int Age { get; set; }
	public string Type { get; set; }
	public string Distillery { get; set; }
	public string Region { get; set; }

	System.Collections.Generic.IEnumerable<(string name, object? value)> __ICanIterate.IterateProperties()
	{
		yield return ("id", Id);
		yield return ("name", Name);
		yield return ("age", Age);
		yield return ("type", Type);
		yield return ("distillery", Distillery);
		yield return ("region", Region);
	}
}
